### ISSUE TITLE
Multithreading with DOtherSide

### ISSUE THREAD

**Issue by White-Oak** [filcuc/DOtherSide#40]
I tried to write some multithreading code, that involves calling bindings' methods and figured Qt doesn't really expect me to use multithreaded code :)

So, libqmlbind has something like [`qmlbind_next_tick`](https://seanchas116.github.io/libqmlbind/group__application__module.html#gac40aade1d2364b787b3b061aa6083512) to put callback to an event queue, at least something like this would be really cool, because as one thread is blocked in QmlEngine::exec(), any work has to be done in other threads.

**Comment by filcuc** [comment]
mind to share an example?

Given that, all Qt applications are mostly single threaded. Any QObject is created and lives inside a thread (and should be destroyed inside the same thread). Furthermore during the load of some Qt plugins some singletons gets created ( and for the rules of C++ gets destroyed only on dll unloading or at application exit). Thus since they gets destroyed at app exit (so on the main thread) they should have been created on the main thread. In other words the Qt main event loop should be locked with the main thread.

I didn't look at the source code of qmlbind_next_tick but i suspect that i works by simply doing a QMetaObject::invoke(...., ConnectionType::Queued) on a QObject living in the main thread. So deferring the execution of a lambda by queuing in the event loop and letting that QObject executing it. Implementing it is simple and straight forward but honestly i'm not convinced that it's the correct solution. 

In a pure Qt C++ application you would spawn a QThread and create a QObject (or move it) in that QThread) and connects its signals and slots. Another options could be to expose some of the QtConcurrentAPI and so allow and async approach. Finally one could split its application between frontend and backend and let communicate through a channel (or any kind of mechanism) in the binded language (be it go channels, rust channels, IPC, msgpack etc).

**Comment by White-Oak** [comment]
@filcuc well, yeah, after some thinking I'm going to conclude, that, yeah, most communications can be done by answering to QML signals, so being in the main thread is given.

The problem  may  come, if I, say, wanted to do some background networking. Even splitting an application  in two parts (backend, frontend) wouldn't help:  frontend is blocked by Qt main thread. One way to achieve communication between QML and an app would probaby be to send signals from QML, maybe, once in a second.

**Comment by filcuc** [comment]
@White-Oak Give a couple of days for working on this. And let me put up an example of a networking application. Like a simple image viewer that works over http. Just to see how we can implement it

**Comment by filcuc** [comment]
@White-Oak 
See https://gist.github.com/filcuc/04e2a2a0b2c8453ed45dae435cacdb79
Ignore that it's written in Nim but you can see that by clicking the download button i start a thread from the Nim threadpool for downloading a page asynchronously. Once downloaded the thread simply emit the pageDownloaded signal. 
Given that i should add support for QImage <-> QVariant from supporting images

**Comment by White-Oak** [comment]
@filcuc 
Thanks, I ported your example https://github.com/White-Oak/qml-rust/blob/master/examples/threaded.rs, it works perfect, the only issue I have is dealing with shared borrows, but that's Rust specific. :)

Okay, I guess, the issue is resolved, just gotta be kept in mind that multithreading should be done this way.

**Comment by richard-ramos** [comment]
@filcuc Hi,
By any chance, do you have this nim example available somewhere:  https://gist.github.com/filcuc/04e2a2a0b2c8453ed45dae435cacdb79?

**Comment by filcuc** [comment]
@richard-ramos i can recreate the example but the best option Is to expose the QMetaObject invokeMethod API

**Comment by richard-ramos** [comment]
Ah, thank you!
In the end I managed to do something using that method in here

https://github.com/status-im/DOtherSide/compare/4d0d6a353c33ff2227b83562a127b3514a7e2169...3ecf2595f1616b36b5de95227f8a7b5581d419c3#diff-96fbe1f349d77063ebd51a5d1b7494e1R721-R726

**Comment by filcuc** [comment]
@richard-ramos  i'm basically working on NimQml for exposing correctly the (already present in DOtherSide) dos_qobject_signal_connect / disconnect. In this way you can simply connect two signal and slots and call the Queued

**Comment by filcuc** [comment]
@richard-ramos latest version added QMetaObject::invokeMethod implementation with custom lambda and support for string based QObject signal connections. I plan to add support in nimqml in this weekend
