### ISSUE TITLE
Ability to use registered signal attributes from QML code

### ISSUE THREAD

**Issue by White-Oak** [filcuc/DOtherSide#45]
The original issue is https://github.com/White-Oak/qml-rust/issues/8.

So the problem is :
- `onPageDownloaded` is a signal `fn pageDownloaded(response: String)`
- `onPageDownloaded: console.log("Page Downloaded "+ response);` fails with an error `ReferenceError: response is not defined`, because attributes' names are not used on registration.

I see three solutions to the original problem:
1. Use `arguments`:

```
onPageDownloaded: console.log("Page downloaded " + arguments[0]);
```

Remember, that in JS you can always check what are the arguments of the function (see [this answer](http://stackoverflow.com/a/2051693/6694565) on SO)
2. Connect signal to function in qml like this

``` qml
  Component.onCompleted: {
    visible = true;
    logic.pageDownloaded.connect(jsPageDownloaded);
  }

  function jsPageDownloaded(response) {
    console.log("Page downloaded " + response);
  }
  // ...
```

This is more verbose.
3. Provide an ability to register attribute name on registration.
Currently `SignalDefinition` consists of signal's name, number of attributes and their types. Is it possible to provide names of attributes as well?

**Comment by filcuc** [comment]
I would go with option 3.
Currently you can already obtain the signal argument from the qml slot.
If i'm not wrong inside a qml handler you can access the argument i-th argument with "arg0", "arg1" etc.
```
onNameChanged: console.log("name is", arg0)
```

**Comment by White-Oak** [comment]
@filcuc ah, yes, so that's the fourth option to access attributes from qml handler.  
Would be awesome to be able to register signals' attributes' names!

**Comment by filcuc** [comment]
@White-Oak 
What's the 4th option? Just for being more clear in what i wrote in my previous message you can access the i-th argument with "arg0" because that's what the current implementation of DOtherSide does. See https://github.com/filcuc/DOtherSide/blob/master/lib/src/DosQMetaObject.cpp#L16

Obviously this is suboptimal given that we use "arg" as prefix instead of the name that the user wrote on its signal definition (however this solution simplify the development of the binding). Give me a couple of days for adding support in C++ (probably on a separate branch).

Thank you
