### ISSUE TITLE
Missing binding of the QAIM::index() and QAIM::createIndex functions

### ISSUE THREAD

**Issue by White-Oak** [filcuc/DOtherSide#46]
It's more of a call of help, then an issue:

[`dataChanged`](https://filcuc.github.io/DOtherSide/group___q_abstract_list_model.html#ga5c7e701ad5e1b980f23f6a0dfbb22078) has, among others, two parameters `topLeft`, `bottomRight` which are [`DosQModelIndex`](https://filcuc.github.io/DOtherSide/group___q_model_index.html). The question is -- how do I get these indexes? By calling `dos_qmodelindex_create` and then `dos_qmodelindex_sibling`? I suppose they won't be valid as they are not connected to the model?

Or maybe, there should be a binding for http://doc.qt.io/qt-5/qabstractitemmodel.html#index or http://doc.qt.io/qt-5/qabstractitemmodel.html#createIndex?

**Comment by filcuc** [comment]
you're right they're missing. I will add them asap.
They were not binded because i usually return a QObject inside the data function a QAIM.
By returning a QObject a the return value of the data() function you don't have to implement the dataChanged. In fact the the QML binds to the property of the QObject (and so they will update when the QObject emit the propertyChanged). 
Sorry it was my fault. I will fix.

**Comment by filcuc** [comment]
@White-Oak my branch qaim should have a fix for this if you want to test it. This will break API/ABI since i've to rework QALM. I've exposed all QAIM functions

**Comment by White-Oak** [comment]
@filcuc thanks, i'll begin implementing them on my side

**Comment by filcuc** [comment]
@white-oak i suggest both of us to keep a separate branch in order to fix bindings and release together. Sound good to you? I don't want to release and break API to existing bindings

**Comment by White-Oak** [comment]
@filcuc we've begin using dotherside as a git submodule, so unless we update it, nothing will break :) Release it when you wish 👍

**Comment by filcuc** [comment]
Fixed in v0.6.0
