### ISSUE TITLE
PreBuilded DOtherSide.dll files invisible for the program

### ISSUE THREAD

**Issue by Dev1lroot** [filcuc/dotherside#85]
I've tried to build DOtherSide.dll primarily, but cmake did not accept MinGW compillers, and said:
"C compliler (gcc.exe) can't even compile a test", then I've tried to build using mason and ninja, and it got me a list of errors in code.
Then I've downloaded prebuilded DOtherSide.dll, but the program does not see it, i think it happened because the program compiled using MinGW, but this DOtherSide using MSVC, I don't wanna use MSVC to compile my programm, and i FUCK MICROSOFT VISUAL STUDIO

**Comment by filcuc** [comment]
@Dev1lroot The prebuilt binaries are made for msvc as you can read from the name of the zip package (msvc2017). The decision to make prebuilt binaries for windows is just convenience and how most window developer expect to find. Supporting prebuild binaries for msvc is quite streightforward given that there're not so much version to support (2017, 2019). GCC and MinGW is another story. That said is funny that you're working on Windows and complain about using Microsoft stuff (Visual Studio).
Regarding the compilation problem you're seeing probably is due to some error in your cmake configuration. Can you create a simple cmake program? i usually test this through QtCreator that ships it's own MinGW version. 
Without any error message i cannot help you further. 
Try to google your error
https://stackoverflow.com/questions/45150172/cmake-error-cmake-was-unable-to-find-a-build-program-corresponding-to-mingw-ma

**Comment by filcuc** [comment]
If there's no feedback i would close this one
